image: node:12.16.1

cache:
  paths:
    - node_modules/

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building deploy package"
    - yarn
    - CI=false yarn build
  cache:
    paths:
      - ./dist

deploy:
  only:
    - tags
    - master
  stage: deploy
  image: python:3.6
  script:
    - echo "Deploying package"
